### ISSUE TITLE
I don't see "advanced options" or "import a list"?

### ISSUE THREAD

**Issue by gingerbeardman** [ssrzz/blocklist#1]
Has twitter removed it?

![58419400-6c255300-8082-11e9-87ad-3b0cc0c09ffd](https://user-images.githubusercontent.com/49612/58419509-b9a1c000-8082-11e9-9d78-ca89206102c4.png)

**Comment by ssrzz** [comment]
> Has twitter removed it?
> 
> ![58419400-6c255300-8082-11e9-87ad-3b0cc0c09ffd](https://user-images.githubusercontent.com/49612/58419509-b9a1c000-8082-11e9-9d78-ca89206102c4.png)

No, switch back to the old version of webpage twitter.

**Comment by gingerbeardman** [comment]
I'll take it up with Twitter, thanks
